version: '3.4'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  postgres:
    platform: linux/amd64
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=serlo
      - POSTGRES_PASSWORD=secret
      - PGPASSWORD=secret
      - POSTGRES_DB=kratos
      